language: node_js
node_js:
  - v10
  - v8
#script: make test-coveralls
#after_script: cat ./coverage/lcov.info | coveralls
before_script:
  - npm install -g grunt-cli

after_success:
- npm run coveralls